#!/usr/bin/env python
# This file is auto generated by setup-autogen.py

from umit.pm.gui.plugins.containers import setup

setup(
    name='SMTPDissector',
    version='1.0',
    author=['Francesco Piccinno'],
    license=['GPL'],
    copyright=['2009 Adriano Monteiro Marques'],
    url='http://blog.archpwn.org',
    scripts=['sources/main.py'],
    start_file='main',
    data_files=[],
    need=['TCPDecoder'],
    provide=['SMTPDissector-1.0'],
    conflict=[],
    description='SMTPDissector plugin.',
    output='smtpdissector.ump',
    audit_type=0,
    protocols=(('tcp', 25), ('smtp', None)),
    vulnerabilities=(('SMTP dissector', {'references': ((None, 'http://en.wikipedia.org/wiki/Simple_Mail_Transfer_Protocol'),), 'description': 'Simple Mail Transfer Protocol (SMTP) is an Internet standard for electronic mail (e-mail) transmission across Internet Protocol (IP) networks.'}),),
)