.TH PacketManipulator 1 "August 17, 2009"

.SH NAME
PacketManipulator \- network scanner

.SH SYNOPSIS
\fBPacketManipulator\fP

.SH DESCRIPTION
\fBPacketManipulator\fP is a network scanning frontend.
.PP
\fBPacketManipulator\fP is developed in the Python programming language, and
its interface is built with the GTK Toolkit.
.PP
The project goal is to develop a frontend that is really useful for
advanced users and easy to be used by newbies. With \fBPacketManipulator\fP,
network admin can forge custom packets and send them over the wire
to analyze the network, sniff on a selected interface or simply edit
a pcap file for further replay.

.SH FILES
.TP
~/.PacketManipulator
Stores configuration settings for \fBPacketManipulator\fP.

.SH BUGS
Please report bugs at http://trac.umitproject.org/newticket?component=PacketManipulator
or visit the bug tracer page at http://trac.umitproject.org/query?component=PacketManipulator

.SH SEE ALSO
http://manipulator.umitproject.org

.SH AUTHORS
Francesco Piccinno <stack.box@gmail.com>
