#! /usr/bin/env python

import os, sys

if sys.platform == 'linux2':
	os.system('python setup.py build')
	wanted_file_exts = [ 'py' , 'so' ]
	
	os.system('svn del PM_copy/umit/pm/backend/bt_sniffer/* --force')
	
	for ext in wanted_file_exts:	
		os.system('cp build/lib.linux-i686-2.6/umit/bluetooth/*.%s PM_copy/umit/pm/backend/bt_sniffer/' % ext)
		
	os.system('svn add PM_copy/umit/pm/backend/bt_sniffer/*')	
		
	# os.system('cp -r btpincrack-v0.3 PacketManipulator/')
	if not os.path.exists('PM_copy/btpincrack-v0.3'):
		os.system('svn copy btpincrack-v0.3 PM_copy/')
else:
	print 'Sorry no can do'






